In [1]:
# check that python and cpp implementations are returning the same acceleration

In [5]:
from solar_system import *
from params import *
from visualise import *
from octree_module import find_acc_cpp
from initial_conditions import generate_spherical_uniform_rs

In [6]:
rs = generate_spherical_uniform_rs()

AssertionError: 

In [4]:
len(rs)

NameError: name 'rs' is not defined

In [5]:
ms = np.array([1] * len(rs))

In [6]:
#python brute force
s = time.time()
py_bf_acc = find_acc_v(rs, ms, len(rs))
f = time.time()
print(f-s)

0.005360841751098633


C:\Users\jackg\Documents\python_projects\solar_system\solar_system.py:52: RuntimeWarning: invalid value encountered in less
  a_mesh = np.where(dist_mesh.reshape(n, n, 1) < particle_radius_mesh.reshape(n, n, 1),


In [7]:
# python octree
centre = np.array([0,0,0])
width = np.max(np.abs(rs)) * 2 + 1
s = time.time()
py_octree = Octree(centre, width, rs, ms)
py_acc = py_octree.find_acc_v(rs, ms)
f = time.time()
print(f-s)

0.11266946792602539


In [9]:
#cpp octree
rs_tuple = tuple(map(tuple, rs))
ms_tuple = tuple(ms)
s = time.time()
cpp_acc = find_acc_cpp(rs_tuple, ms_tuple, (p.unit_mass_particle_radius, p.qt, p.G))
f = time.time()
print(f-s)

0.005984306335449219


In [10]:
cpp_acc = np.array(cpp_acc)

In [11]:
fractional_diff = (cpp_acc - py_acc) / py_acc

In [12]:
diff = cpp_acc - py_acc

In [13]:
diff

array([[-1.44549604e-04,  1.88563273e-04, -2.72938445e-04],
       [ 2.80208856e-04, -1.12797823e-04, -2.91445808e-04],
       [-9.48303051e-05, -5.29318202e-04,  1.08568749e-03],
       [-4.34028812e-04,  4.78638318e-04,  5.99239005e-04],
       [ 3.51855664e-05, -3.68713424e-05, -3.87629421e-04],
       [-3.89796080e-04, -7.85491563e-04,  4.36760340e-06],
       [-7.69355763e-05,  1.59855905e-04,  3.57139315e-04],
       [ 7.59185751e-04,  3.52533776e-03, -1.50398139e-03],
       [-5.97379701e-04, -2.31463656e-04, -1.11127746e-03],
       [-5.92215071e-05, -1.04364838e-04,  2.14581505e-04],
       [ 6.62107277e-04, -5.76025388e-04, -2.46414609e-04],
       [ 2.87394993e-04,  5.39099246e-05,  1.67926553e-03],
       [-3.95072161e-04, -3.59848962e-04,  1.48989118e-04],
       [-1.90208705e-04,  5.62048193e-05,  2.62151749e-04],
       [-3.55808287e-04, -3.24147959e-05, -4.60257441e-04],
       [-6.88039070e-05,  1.39703962e-04,  3.92506571e-04],
       [ 2.34803526e-04,  1.02276476e-04

In [19]:
for i in range(len(rs)):
    print(fractional_diff[i])
    print(py_acc[i])
    print(cpp_acc[i])
    print("\n")

[ 0.00441466 -0.05643459 -0.24385638]
[ 0.0234397   0.01868761 -0.00890489]
[ 0.02354318  0.01763298 -0.00673338]


[-0.00510612 -0.05582346  0.0022629 ]
[ 0.0465866  -0.0062804   0.01650699]
[ 0.04634872 -0.00592981  0.01654434]


[-0.00304267  0.00892215 -0.02659742]
[0.00848048 0.01104763 0.03470977]
[0.00845468 0.0111462  0.03378658]


[0.00640505 0.13707566 0.02573218]
[ 0.05271916  0.01119509 -0.01670877]
[ 0.05305683  0.01272966 -0.01713872]


[-0.10803867 -0.02678346 -0.02842793]
[-0.00830903  0.0178449   0.0363839 ]
[-0.00741133  0.01736695  0.03534958]


[-0.03202237 -0.08698301 -0.03436211]
[-0.01253676  0.00918425  0.04546724]
[-0.0121353   0.00838538  0.04390489]


[-0.06438678 -0.01326645  0.18435174]
[-0.01979661 -0.02489093 -0.00699275]
[-0.01852197 -0.02456072 -0.00828187]


[-0.03686688 -0.02125922 -0.0212841 ]
[ 0.01290518 -0.02275305  0.01138127]
[ 0.0124294  -0.02226933  0.01113903]


[-0.26065888  0.01494096 -0.02513646]
[ 0.00401854  0.01671598 -0.02756496]
[ 0.0

In [1]:
rs

NameError: name 'rs' is not defined

In [11]:
for r in rs:
    print("{", r[0], ",", r[1], ",", r[2], "},")

{ -17.904878799832673 , 27.749553008844924 , 3.191866827004536 },
{ 30.722530086990766 , 21.37306327544428 , -12.85193457721086 },
{ 29.758142563180314 , 15.896283817031133 , -17.361971033662535 },
{ -13.59783773542579 , -20.15568443347703 , 18.32540307569031 },
{ 23.863153907877038 , -12.237338239685654 , 8.91422570801456 },
{ -11.781177813684279 , -7.200682454491483 , 27.308151140527908 },
{ -7.751771877065066 , 41.257496242590584 , 15.017483675731958 },
{ 4.496477460954082 , 43.51445979391919 , 11.13374850776857 },
{ 24.547415237560635 , -20.756841129927043 , -9.28655709040868 },
{ -14.608044262767864 , -41.975660701314844 , 14.93352651306863 },
{ -11.002660555770118 , 28.707351865539028 , 8.945632850540747 },
{ -15.323588629083568 , 10.796390223601056 , 37.924935407288025 },
{ -42.50776895630206 , 5.1267406248857395 , 0.6883943585070561 },
{ -20.86067592208471 , 4.855069384741468 , -25.188302155530096 },
{ 10.71634700323915 , -0.21863035009368043 , -23.575285029517456 },
{ 16.17035

{ 38.44688876508309 , -8.711836784062083 , 23.132773407207736 },
{ -24.30179187096447 , -19.339180456889856 , 3.251265236178489 },
{ -11.65010032585014 , 2.4728187211191446 , -20.099503363409784 },
{ 12.348306670056644 , -32.33452033131329 , -23.53879568799608 },
{ 11.504367744329562 , -0.7242710424005766 , -3.485541836449105 },
{ 1.051705964218053 , -10.111411124726839 , 17.857114389858832 },
{ -31.949395858438713 , -22.812818510817788 , 17.372549869678142 },
{ -4.389012520550228 , 16.692791418525296 , 39.3481398126164 },
{ -1.102599608649131 , -15.123212409940816 , -30.864776072013868 },
{ 7.0667802649953115 , 10.515765464277216 , 45.89283269423042 },
{ 39.64242020767379 , -2.401759191130535 , 29.04370534650515 },
